### ISSUE TITLE
ERF-dynamic-display-610day

### ISSUE THREAD

**Issue by aHartmanTheGisGuy** [noaa-nws-cpc/github#3]
Processing codes that produce ERF 6-10 day outlooks used in the dynamic display.

**Comment by mikecharles** [comment]
@aHartmanTheGisGuy would this code be for 6-10day and 8-14day? Is there an existing svn repo for this code?

**Comment by aHartmanTheGisGuy** [comment]
Mike,

There is no repo for the 6-10 and 8-14 interactive displays presently, per
an email exchange we had earlier this year. I also looked again beforehand
just to double-check and didn't see anything that jumped out. I do have a
couple of questions though.

1. Should I add all folders within the directory or only those containing
scripts I plan to change? For example, there is a "library" folder that is
quite large due to a couple thousand geotiffs.
2. Will any directories I ignore not be accessible to scripts while testing
them?

Adam H.

*Adam T. Hartman*
*Atmospheric Scientist / GIS Specialist*
*INNOVIM, LLC*
*NOAA / NWS / NCEP / Climate Prediction Center*
*Email:** adam.hartman@noaa.gov <adam.hartman@noaa.gov>*
*Office Phone:* *(301) 683-1314 (ext. 3306)*
*Cell Phone:** (757) 408-5480*

**Comment by mikecharles** [comment]
> Mike, There is no repo for the 6-10 and 8-14 interactive displays presently, per an email exchange we had earlier this year. I also looked again beforehand just to double-check and didn't see anything that jumped out. I do have a couple of questions though. 

Ok

> 1. Should I add all folders within the directory or only those containing scripts I plan to change? For example, there is a "library" folder that is quite large due to a couple thousand geotiffs. 

The repo will need to contain all files necessary to recreate a copy of the code and run the application to completion. That doesn't include things that are temporary (log files, PNG/binary/shapefile output, etc.), and things that are created when compiling/building the code (may not apply here).

We should consider moving the files that are currently in the `library/` directory to a centralized library directory (like `/cpc/data/library`). I can work with you on how to do this.

> 2. Will any directories I ignore not be accessible to scripts while testing them?

Yes, if you leave directories out of the repo, when you clone that repo somewhere else you'll be missing those directories.

**Comment by mikecharles** [comment]
Done: https://github.com/noaa-nws-cpc/erf-dynamic-display-tool

Please let me know when you're ready to import so we can go over what to do with the `library/` directory.

Thanks

**Comment by aHartmanTheGisGuy** [comment]
Mike,

Agreed. I am available this week and next week to discuss moving the two
library directories to a centralized location. On the coding side, it
should be as simple as changing the pointers in the configure perl scripts.
Should I push the existing code to the repo before I begin making changes
and testing it or should I go ahead and make changes, test it over the next
couple weeks, then push the updated code once I am finished?

Adam

*Adam T. Hartman*
*Atmospheric Scientist / GIS Specialist*
*INNOVIM, LLC*
*NOAA / NWS / NCEP / Climate Prediction Center*
*Email:** adam.hartman@noaa.gov <adam.hartman@noaa.gov>*
*Office Phone:* *(301) 683-1314 (ext. 3306)*
*Cell Phone:** (757) 408-5480*

**Comment by mikecharles** [comment]
> Should I push the existing code to the repo before I begin making changes and testing it or should I go ahead and make changes, test it over the next couple weeks, then push the updated code once I am finished?

I would prefer if the code was cleaned up and the library files were external first. We don't want to commit those to the repo at all, because once they're committed they're in the history for good.

What are the two directories, so I can take a look and see what's in them?

**Comment by aHartmanTheGisGuy** [comment]
/cpc/prod/cpcfcst/processes/erf_dyn_disp_tool_RH6/pendleton_610test/library
/cpc/prod/cpcfcst/processes/erf_dyn_disp_tool_RH6/pendleton_814test/library

*Adam T. Hartman*
*Atmospheric Scientist / GIS Specialist*
*INNOVIM, LLC*
*NOAA / NWS / NCEP / Climate Prediction Center*
*Email:** adam.hartman@noaa.gov <adam.hartman@noaa.gov>*
*Office Phone:* *(301) 683-1314 (ext. 3306)*
*Cell Phone:** (757) 408-5480*

**Comment by mikecharles** [comment]
I've copied the data into this dir:

    $DATA_IN/library/dynamic-display-tool/ERF

Let me know if that works for you

**Comment by aHartmanTheGisGuy** [comment]
Mike,

I have finished testing the ERF processing scripts and they look to be
good. Can we meet sometime this week to go over the push to GitHub? I also
want you to take a look at the directories that I am ignoring and discuss
the migration of the library to the centralized location you mentioned in
the previous email. Let me know a time that works for you!

Best wishes,

Adam H.

*Adam T. Hartman*
*Atmospheric Scientist / GIS Technical Specialist*
*INNOVIM, LLC*
*NOAA - NWS - NCEP Climate Prediction Center*
*Email:** adam.hartman@noaa.gov <adam.hartman@noaa.gov>*
*Desk Phone:* *(301) 683-1314 (ext. 3306)*
*Cell Phone:** (757) 408-5480*

**Comment by mikecharles** [comment]
Great, Tue, Thu, or Fri are good with me. You can put something in my calendar ;-)

**Comment by aHartmanTheGisGuy** [comment]
Yes sir. I will take a look shortly and shoot you a notification via email.
Thank you!

Adam H.

*Adam T. Hartman*
*Atmospheric Scientist / GIS Technical Specialist*
*INNOVIM, LLC*
*NOAA - NWS - NCEP Climate Prediction Center*
*Email:** adam.hartman@noaa.gov <adam.hartman@noaa.gov>*
*Desk Phone:* *(301) 683-1314 (ext. 3306)*
*Cell Phone:** (757) 408-5480*
